- name: "apt setup"
  # reference: https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
  hosts: all
  tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Update all Debian/Ubuntu packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
